
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - statefulset.yaml
  - service.yaml

labels:
  - includeSelectors: true
    pairs:
      app: postgresql

commonAnnotations:
  version: "13.1"

images:
  - name: postgres
    newTag: "13.1"
  - name: wrouesnel/postgres_exporter
    newTag: "v0.8.0"
