apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
stringData:
  PGDATA: "/var/lib/postgresql/data/pgdata"
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: supersecret
