version: '3'

tasks:

  build:
    desc: Build code
    cmds:
      - go build

  run:
    desc: Run application
    cmds:
      - godotenv -f local.env go run main.go

  container-build:
    desc: Build http-server container image
    requires:
      vars: [ VERSION ]
    cmds:
      - docker buildx build . -f Dockerfile -t bygui86/http-server:{{.VERSION}} --platform linux/amd64,linux/arm64
      - docker buildx build . -f Dockerfile -t bygui86/http-server:{{.VERSION}} --load

  container-push:
    desc: Push http-server container image to container registry
    requires:
      vars: [ VERSION ]
    cmds:
      - docker push bygui86/http-server:{{.VERSION}}

  container-build-push:
    desc: Build & push http-server container image to container registry
    requires:
      vars: [ VERSION ]
    cmds:
      - docker buildx build . -f Dockerfile -t bygui86/http-server:{{.VERSION}} --platform linux/amd64,linux/arm64 --push

  deploy-pg:
    desc: Deploy PostgreSQL to K8s
    cmds:
      - kustomize build kube/postgres/ | kubectl apply -f -

  delete-pg:
    desc: Delete PostgreSQL from K8s
    cmds:
      - kustomize build kube/postgres/ | kubectl delete -f -

  follow-logs-pg:
    desc: Show and follow PostgreSQL logs from K8s
    cmds:
      - kubectl logs -l app=postgresql --tail 10000 -f

  deploy:
    desc: Deploy application to K8s
    cmds:
      - kustomize build kube/ | kubectl apply -f -

  delete:
    desc: Delete application from K8s
    cmds:
      - kustomize build kube/ | kubectl delete -f -

  follow-logs:
    desc: Show and follow application logs from K8s
    cmds:
      - kubectl logs -l app=http-server --tail 10000 -f
