version: '3'

tasks:

  build:
    desc: Build http-client container image
    requires:
      vars: [ VERSION ]
    cmds:
      - docker buildx build . -f Dockerfile -t bygui86/http-client:{{.VERSION}} --platform linux/amd64,linux/arm64
      - docker buildx build . -f Dockerfile -t bygui86/http-client:{{.VERSION}} --load

  push:
    desc: Push http-client container image to container registry
    requires:
      vars: [ VERSION ]
    cmds:
      - docker push bygui86/http-client:{{.VERSION}}

  build-push:
    desc: Build & push http-client container image to container registry
    requires:
      vars: [ VERSION ]
    cmds:
      - docker buildx build . -f Dockerfile -t bygui86/http-client:{{.VERSION}} --platform linux/amd64,linux/arm64 --push
