apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-client
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: http-client
  template:
    metadata:
      labels:
        app: http-client
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: http-client
          image: bygui86/http-client
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: http-client
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 9090
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
