
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

labels:
  - includeSelectors: true
    pairs:
      app: http-server

commonAnnotations:
  version: v1.0.0

images:
  - name: bygui86/http-server
    newTag: v1.0.0
